[[plugins]]
package = "@netlify/plugin-sitemap"

[plugins.inputs]
buildDir = ""
baseUrl = "https://fabbrogorgonzola.netlify.app"

[build]
command = "npm run build && echo 'Sitemap generation completed'"
